### ISSUE TITLE
Change Port for cloud server

### ISSUE THREAD

**Issue by Memphiz** [toniebox-reverse-engineering/hackiebox_cfw_ng#44]
I am using Teddycloud but due to the setup of my network and virtual machines the port 443 is taken by a different service already. I was not able to successfully forward via virtual host yet. Is there any chance that you could provide a patch for changing the port for the cloud / teddycloud server inside the firmware?

I have tried this myself by changing all occurrences of 0xBB 0x01 to 0xBC 0x01 in the firmware binary (should have changed all occurrences of the ushort 443 to 444). But this didn't work and might have been a bit to naive (i didn't notice any difference in all those 8 different binaries whatsoever). I have no disassambler for armv7 sadly to dig into it.

**Comment by SciLor** [comment]
I don't know if this is possible that easily. But we will check that. It may be very complicated to change the port, if this is handled within the cc3200 base firmware.

You could try to create your own altUrl patch, but with adding the port at the end. Beware that the string doesn't get longer than the original dns name.

Alternatively, if you are using docker you can easily create a macvlan, so your container gets its own ip-address.

**Comment by Memphiz** [comment]
I tried your suggestion and changed the altUrl patch to something like blah.rev:444 (obeying the maximum number of characters for each string of course). Well no connection to the cloud at all with that (neither on 443, nor on 444). But it was worth a try :)

**Comment by bluenazgul** [comment]
If you use Docker it is possible to use macvlan this will you allows to use
a dedicated IP and this allows you to use Port 80 and 443 even 8f the Host
is allready using them

Memphiz ***@***.***> schrieb am Mi., 20. Sept. 2023, 21:55:

**Comment by Memphiz** [comment]
Yeah I know. Atm I use lxc containers but having multiple services in one container. Due to storage setup and other surrounding circumstances the teddy cloud has to run in a container that already has a reverse proxy on port 443.
I am a step forward in reverse proxying teddycloud via virtual host though. But it’s unstable atm (sometimes tonies are not correctly downloaded from toniecloud on the first go or I get temporarily HTTP Response 401 Unauthorized from toniecloud).

So yes i can come up with a container based solution eventually by refactoring my network structure a bit.

So thx for looking into the port change patch. If it is not solvable that’s not the end of possible solutions for sure.

**Comment by Memphiz** [comment]
I added a second ip to my container and came up with a solution on teddycloud side here:

https://github.com/toniebox-reverse-engineering/teddycloud/pull/55
