### ISSUE TITLE
File not Found when uploading to flash

### ISSUE THREAD

**Issue by offle** [toniebox-reverse-engineering/hackiebox_cfw_ng#47]
Hi,
when I want to Upload the ca.der from Teddycloud as /cert/c2.der into the Box's flash I receive the following error on the URL
`http://10.0.0.184/api/upload/flash-file?overwrite=on&filepath=%2Fcert%2Fc2.der&filesize=787`

```
File Not Found

URI: /api/upload/flash-file
Method: POST
Arguments: 3
 overwrite: on
 filepath: /cert/c2.der
 filesize: 787
```

**Comment by SciLor** [comment]
This is the case when there is nothing to overwrite. It should be fine if you disable the overwrite option.
